name: Deploy

on: workflow_dispatch
  #push:
    #branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  deploy:

    runs-on: self-hosted

    steps:
    - uses: actions/checkout@v4
    - name: checkout directory
      run: cd ~/shapka

    - name: build
      run: cargo build

    - name: kill old
      continue-on-error: true
      run: fuser -k 8000/tcp

      # RUNNER_TRACKING_ID="" is so that when the runner finishes the workflow, the detached screen session is not killed
      # https://stackoverflow.com/questions/76282174/starting-a-tmux-session-from-github-action-doesnt-persist-once-the-action-compl
      # screen -d -m is so that the server is ran in a detached shell and therefore not terminated
    - name: run
      run: |
        RUNNER_TRACKING_ID=""
        screen -d -m cargo run
        sleep 5

